### ISSUE TITLE
feature: add `retry` and `timeout` to the action

### ISSUE THREAD

**Issue by Anmol1696** [cosmology-tech/starship-action#14]
## Overview
There seems to be transient errors when running Starship in the gh action.

## Proposal
Add `retry` and `timeout` for the infra setup
```yaml
- name: Setup Test infra
  id: starship-action
  uses: cosmology-tech/starship-action@0.2.13
  with:
    values: tests/starship/configs/ci.yaml
    port-forward: true
    version: 0.1.42
    timeout: 10m
    retry: 2
```

Wait only till the timeout, but if unsucessful, then retry as many number of times as mentioned.
Defaults: `timeout: 10m`, `retry: 1`
